xrandr -s 1920x1080
xrandr --dpi 144
xbacklight -set 40
xrdb -merge ~/.Xresources
start-pulseaudio-x11 &
setxkbmap -layout us -variant alt-intl -option compose:ralt -option caps:swapescape -option nodeadkeys -option terminate:ctrl_alt_bksp
xinput --disable 12
exec awesome
