#!/bin/sh
# Created by Guillaume Quittet on 01-28-2017
# Run or stop virtualbox
#
# Copyright (C) 2017  Guillaume Quittet
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

username=$(whoami)
case $1 in
    --start) sudo mkdir /mnt/{$username,$username/SSD} && sudo mount /dev/sdb1 /mnt/$username/SSD
	     nohup virtualbox > /dev/null 2>&1 &
	     disown
	     ;;
    -s) sudo mkdir /mnt/{$username,$username/SSD} && sudo mount /dev/sdb1 /mnt/$username/SSD
	nohup virtualbox > /dev/null 2>&1 &
	disown
	;;
    --kill) sudo umount /mnt/$username/SSD && sudo rm -r /mnt/$username
	    ;;
    -k) sudo umount /mnt/$username/SSD && sudo rm -r /mnt/$username
	;;
    -h) echo -e "\nvb-script [OPTION]\n\n[OPTION]: {-s|--start|-k|--kill}\n\nGet help: vb-script {-h|--help}\n"
	;;
    --help) echo -e "\nvb-script [OPTION]\n\n[OPTION]: {-s|--start|-k|--kill}\n\nGet help: vb-script {-h|--help}\n"
	    ;;
    *) echo "Unknown command."
       ;;
esac
